// Images from dummyjson CDN and fakestoreapi
const d = (path: string, n = 1) =>
  `https://cdn.dummyjson.com/product-images/${path}/${n}.webp`

const f = (file: string) => `https://fakestoreapi.com/img/${file}`

// Standard women's body measurements per size (cm)
const BASE: Record<string, { chest: number; waist: number; hip: number }> = {
  XS:  { chest: 80,  waist: 62, hip: 88  },
  S:   { chest: 84,  waist: 66, hip: 92  },
  M:   { chest: 88,  waist: 70, hip: 96  },
  L:   { chest: 96,  waist: 78, hip: 104 },
  XL:  { chest: 104, waist: 86, hip: 112 },
  XXL: { chest: 108, waist: 90, hip: 116 },
}

// Length offset by size (garments run slightly longer in larger sizes)
const LEN: Record<string, number> = { XS: -2, S: -1, M: 0, L: 1, XL: 2, XXL: 3 }

// Generate a sizing chart for a garment: sizes = which sizes to include, baseLength = M-size garment length in cm
function sc(
  sizes: string[],
  baseLength: number,
): Record<string, { chest: number; waist: number; hip: number; length: number }> {
  return Object.fromEntries(
    sizes
      .filter(s => BASE[s])
      .map(s => [s, { ...BASE[s], length: baseLength + (LEN[s] ?? 0) }]),
  )
}

export const SEED_PRODUCTS = [

  // ─── DRESSES (original 10) ──────────────────────────────────────────────────
  {
    name: 'Pea Print Dress',
    slug: 'pea-print-dress',
    category: 'Dresses',
    description: 'A stylish and comfortable dress with a playful pea pattern. Light fabric and relaxed fit make it a great choice for day-to-day wear.',
    price: 49.99,
    colours: ['Green', 'Multi'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasion: ['casual', 'everyday', 'brunch'],
    stock: 6,
    gradient: 'from-green-100 via-emerald-50 to-green-200',
    isNew: false, isSale: false,
    tags: ['casual', 'print', 'everyday', 'comfortable'],
    rating: 4.9, reviewCount: 103,
    images: [d('womens-dresses/dress-pea')],
    sizingChart: sc(['XS','S','M','L','XL','XXL'], 118),
  },
  {
    name: 'Marni Red & Black Suit Dress',
    slug: 'marni-red-black-suit-dress',
    category: 'Dresses',
    description: 'A sophisticated suit ensemble featuring bold red and black tones. Perfect for power dressing at work or formal events.',
    price: 179.99,
    colours: ['Red', 'Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    occasion: ['work', 'formal', 'meeting'],
    stock: 62,
    gradient: 'from-red-900 via-red-800 to-gray-900',
    isNew: true, isSale: false,
    tags: ['suit', 'power-dressing', 'formal', 'bold'],
    rating: 4.5, reviewCount: 55,
    images: [d('womens-dresses/marni-red-&-black-suit')],
    sizingChart: sc(['XS','S','M','L'], 96),
  },
  // ─── DRESSES (new — each uses a unique image not seen above) ────────────────

  // ─── TOPS (original 3) ──────────────────────────────────────────────────────
  {
    name: 'Boat Neck Stretch Top',
    slug: 'boat-neck-stretch-top',
    category: 'Tops',
    description: 'Rayon-spandex blend with a flattering boat neck and V detail. Lightweight fabric with great stretch for all-day comfort. A wardrobe essential.',
    price: 9.85,
    colours: ['Black', 'White', 'Navy', 'Red', 'Ivory'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasion: ['casual', 'work', 'everyday'],
    stock: 120,
    gradient: 'from-slate-100 via-gray-50 to-slate-200',
    isNew: false, isSale: false,
    tags: ['stretch', 'casual', 'everyday', 'versatile'],
    rating: 4.3, reviewCount: 210,
    images: [f('71z3kpMAYsL._AC_UY879_t.png')],
    sizingChart: sc(['XS','S','M','L','XL','XXL'], 60),
  },
  {
    name: 'Moisture-Wicking Active Top',
    slug: 'moisture-wicking-active-top',
    category: 'Tops',
    description: 'Highly breathable polyester top with moisture-wicking fabric. Slim, feminine silhouette. Perfect for active days or casual outings.',
    price: 7.95,
    colours: ['Blue', 'Black', 'Purple', 'Pink'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['casual', 'everyday', 'sport'],
    stock: 85,
    gradient: 'from-blue-100 via-sky-50 to-indigo-100',
    isNew: false, isSale: true,
    salePrice: 5.95,
    tags: ['active', 'breathable', 'casual', 'sporty'],
    rating: 4, reviewCount: 167,
    images: [f('51eg55uWmdL._AC_UX679_t.png')],
    sizingChart: sc(['XS','S','M','L','XL'], 58),
  },
  {
    name: 'V-Neck Graphic Cotton Tee',
    slug: 'v-neck-graphic-cotton-tee',
    category: 'Tops',
    description: 'Cotton-spandex casual V-neck with letter print detailing. Versatile seasonal staple that pairs with jeans, skirts, or trousers.',
    price: 12.99,
    colours: ['Black', 'White', 'Grey', 'Rose'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasion: ['casual', 'everyday', 'weekend'],
    stock: 200,
    gradient: 'from-rose-50 via-pink-50 to-rose-100',
    isNew: false, isSale: false,
    tags: ['cotton', 'casual', 'graphic', 'everyday'],
    rating: 3.8, reviewCount: 93,
    images: [f('61pHAEJ4NML._AC_UX679_t.png')],
    sizingChart: sc(['XS','S','M','L','XL','XXL'], 62),
  },

  // ─── TOPS (new — each uses a unique image not seen above) ───────────────────
  {
    name: 'Linen Button-Down Blouse',
    slug: 'linen-button-down-blouse',
    category: 'Tops',
    description: 'A relaxed linen button-down blouse with a slightly oversized fit and rolled-sleeve cuffs. The perfect warm-weather layering piece.',
    price: 45.99,
    colours: ['White', 'Sand', 'Sage', 'Sky Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasion: ['casual', 'work', 'beach', 'smart-casual'],
    stock: 88,
    gradient: 'from-stone-50 via-amber-50 to-stone-100',
    isNew: true, isSale: false,
    tags: ['linen', 'blouse', 'casual', 'button-down'],
    rating: 4.7, reviewCount: 156,
    images: [d('tops/blue-frock', 2)],
    sizingChart: sc(['XS','S','M','L','XL','XXL'], 62),
  },
  {
    name: 'Silk Cami Top',
    slug: 'silk-cami-top',
    category: 'Tops',
    description: 'A luxuriously smooth silk-finish cami with adjustable spaghetti straps and delicate lace trim. Wear alone or layered under a blazer.',
    price: 64.99,
    colours: ['Champagne', 'Black', 'Dusty Rose', 'Cobalt'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['casual', 'evening', 'date', 'work'],
    stock: 55,
    gradient: 'from-amber-50 via-yellow-50 to-amber-100',
    isNew: false, isSale: false,
    tags: ['silk', 'cami', 'elegant', 'versatile'],
    rating: 4.6, reviewCount: 203,
    images: [d('tops/girl-summer-dress', 2)],
    sizingChart: sc(['XS','S','M','L','XL'], 55),
  },
  {
    name: 'Cropped Knit Sweater',
    slug: 'cropped-knit-sweater',
    category: 'Tops',
    description: 'A cosy cropped knit sweater in soft ribbed fabric. Relaxed fit with a rounded neckline — pairs perfectly with high-waisted skirts and trousers.',
    price: 55.99,
    colours: ['Cream', 'Camel', 'Sage', 'Burgundy', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['casual', 'everyday', 'work', 'autumn'],
    stock: 72,
    gradient: 'from-amber-100 via-stone-50 to-amber-200',
    isNew: false, isSale: true,
    salePrice: 42.99,
    tags: ['knit', 'cropped', 'cosy', 'ribbed'],
    rating: 4.8, reviewCount: 287,
    images: [d('tops/gray-dress', 2)],
    sizingChart: sc(['XS','S','M','L','XL'], 50),
  },
  {
    name: 'Off-Shoulder Ruffle Blouse',
    slug: 'off-shoulder-ruffle-blouse',
    category: 'Tops',
    description: 'A romantic off-shoulder blouse with flutter ruffle sleeves and an elasticated neckline. Lightweight woven fabric with a floaty, feminine feel.',
    price: 49.99,
    colours: ['White', 'Blush', 'Sky Blue', 'Sage'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['casual', 'party', 'brunch', 'date'],
    stock: 44,
    gradient: 'from-rose-50 via-pink-50 to-rose-100',
    isNew: true, isSale: false,
    tags: ['off-shoulder', 'ruffle', 'feminine', 'blouse'],
    rating: 4.5, reviewCount: 122,
    images: [d('tops/short-frock', 2)],
    sizingChart: sc(['XS','S','M','L','XL'], 56),
  },
  {
    name: 'Floral Print Wrap Blouse',
    slug: 'floral-print-wrap-blouse',
    category: 'Tops',
    description: 'A pretty wrap-front blouse in a vibrant floral print with a V-neckline and tie waist. Versatile enough for work or a weekend brunch.',
    price: 54.99,
    colours: ['Pink Floral', 'Blue Floral', 'Multi'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['work', 'casual', 'brunch', 'smart-casual'],
    stock: 60,
    gradient: 'from-pink-100 via-rose-50 to-pink-200',
    isNew: false, isSale: false,
    tags: ['floral', 'wrap', 'blouse', 'print'],
    rating: 4.4, reviewCount: 98,
    images: [d('tops/tartan-dress', 2)],
    sizingChart: sc(['XS','S','M','L','XL'], 60),
  },
  {
    name: 'Ribbed Turtleneck Top',
    slug: 'ribbed-turtleneck-top',
    category: 'Tops',
    description: 'A sleek ribbed turtleneck in fine-knit fabric. The close fit and elegant neck make it a timeless layering piece for cooler months.',
    price: 38.99,
    colours: ['Black', 'Ivory', 'Camel', 'Navy', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasion: ['casual', 'work', 'everyday', 'autumn', 'winter'],
    stock: 110,
    gradient: 'from-gray-100 via-slate-50 to-gray-200',
    isNew: false, isSale: false,
    tags: ['turtleneck', 'ribbed', 'classic', 'layering'],
    rating: 4.9, reviewCount: 341,
    images: [d('tops/blue-frock', 3)],
    sizingChart: sc(['XS','S','M','L','XL','XXL'], 58),
  },
  {
    name: 'Oversized Linen Shirt',
    slug: 'oversized-linen-shirt',
    category: 'Tops',
    description: 'A relaxed oversized linen shirt with a classic collar, chest pocket, and drop shoulders. Wear tucked in, tied at the waist, or open over a swimsuit.',
    price: 59.99,
    colours: ['White', 'Sand', 'Sage', 'Soft Blue', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['casual', 'beach', 'holiday', 'everyday'],
    stock: 95,
    gradient: 'from-blue-50 via-sky-50 to-blue-100',
    isNew: false, isSale: false,
    tags: ['linen', 'oversized', 'shirt', 'relaxed'],
    rating: 4.7, reviewCount: 265,
    images: [d('tops/girl-summer-dress', 3)],
    sizingChart: sc(['XS','S','M','L','XL'], 68),
  },
  {
    name: 'Tie-Front Crop Top',
    slug: 'tie-front-crop-top',
    category: 'Tops',
    description: 'A flirty crop top with a knotted tie front and short sleeves. Light cotton fabric and relaxed fit — ideal for pairing with high-waisted bottoms.',
    price: 34.99,
    colours: ['White', 'Black', 'Coral', 'Mint', 'Yellow'],
    sizes: ['XS', 'S', 'M', 'L'],
    occasion: ['casual', 'beach', 'summer', 'everyday'],
    stock: 78,
    gradient: 'from-teal-50 via-emerald-50 to-teal-100',
    isNew: true, isSale: false,
    tags: ['crop', 'tie-front', 'casual', 'summer'],
    rating: 4.3, reviewCount: 174,
    images: [d('tops/gray-dress', 3)],
    sizingChart: sc(['XS','S','M','L'], 42),
  },
  {
    name: 'V-Neck Satin Blouse',
    slug: 'v-neck-satin-blouse',
    category: 'Tops',
    description: 'A polished v-neck blouse in satin-weave fabric with a fluid drape. Tucks neatly into tailored trousers for a sleek office look.',
    price: 74.99,
    colours: ['Ivory', 'Black', 'Blush', 'Navy', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['work', 'formal', 'date', 'evening'],
    stock: 52,
    gradient: 'from-neutral-100 via-stone-50 to-neutral-200',
    isNew: false, isSale: false,
    tags: ['satin', 'blouse', 'v-neck', 'elegant'],
    rating: 4.6, reviewCount: 131,
    images: [d('tops/short-frock', 3)],
    sizingChart: sc(['XS','S','M','L','XL'], 62),
  },
  {
    name: 'Puff Sleeve Blouse',
    slug: 'puff-sleeve-blouse',
    category: 'Tops',
    description: 'A statement blouse with voluminous puff sleeves and a fitted cuff. Romantic and contemporary, it pairs effortlessly with tailored trousers or a midi skirt.',
    price: 55.99,
    colours: ['White', 'Sage', 'Dusty Lilac', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['work', 'casual', 'party', 'smart-casual'],
    stock: 39,
    gradient: 'from-violet-50 via-purple-50 to-violet-100',
    isNew: true, isSale: false,
    tags: ['puff-sleeve', 'blouse', 'statement', 'romantic'],
    rating: 4.7, reviewCount: 108,
    images: [d('tops/tartan-dress', 3)],
    sizingChart: sc(['XS','S','M','L','XL'], 60),
  },

  // ─── BOTTOMS ─────────────────────────────────────────────────────────────────
  {
    name: 'Wide-Leg Linen Trousers',
    slug: 'wide-leg-linen-trousers',
    category: 'Bottoms',
    description: 'Effortlessly chic wide-leg trousers in breathable linen. High-waisted silhouette with side pockets and a relaxed drape for everyday elegance.',
    price: 79.99,
    colours: ['Ivory', 'Black', 'Camel', 'Sage'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['casual', 'work', 'smart-casual'],
    stock: 45,
    gradient: 'from-amber-50 via-stone-50 to-amber-100',
    isNew: true, isSale: false,
    tags: ['linen', 'wide-leg', 'trousers', 'relaxed'],
    rating: 4.6, reviewCount: 88,
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4b4657?auto=format&fit=crop&w=600&q=80'],
    sizingChart: sc(['XS','S','M','L','XL'], 100),
  },
  {
    name: 'Satin Midi Skirt',
    slug: 'satin-midi-skirt',
    category: 'Bottoms',
    description: 'Luxuriously smooth satin midi skirt with a wrap front and slip silhouette. Elegant enough for evenings, versatile enough for daytime styling.',
    price: 65.99,
    colours: ['Champagne', 'Black', 'Dusty Rose', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['formal', 'casual', 'date', 'evening'],
    stock: 38,
    gradient: 'from-yellow-50 via-amber-50 to-yellow-100',
    isNew: true, isSale: false,
    tags: ['satin', 'midi', 'skirt', 'elegant'],
    rating: 4.8, reviewCount: 112,
    images: ['https://images.unsplash.com/photo-1583496661160-fb5218afa9a0?auto=format&fit=crop&w=600&q=80'],
    sizingChart: sc(['XS','S','M','L','XL'], 78),
  },
  {
    name: 'Denim Mini Skirt',
    slug: 'denim-mini-skirt',
    category: 'Bottoms',
    description: 'Classic denim mini skirt with a button-front closure and frayed hem. A timeless casual staple that pairs with anything in your wardrobe.',
    price: 44.99,
    colours: ['Light Wash', 'Dark Wash', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['casual', 'everyday', 'weekend'],
    stock: 60,
    gradient: 'from-blue-200 via-indigo-100 to-blue-300',
    isNew: false, isSale: true,
    salePrice: 32.99,
    tags: ['denim', 'mini', 'casual', 'classic'],
    rating: 4.3, reviewCount: 156,
    images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f43?auto=format&fit=crop&w=600&q=80'],
    sizingChart: sc(['XS','S','M','L','XL'], 40),
  },
  {
    name: 'Pleated Midi Skirt',
    slug: 'pleated-midi-skirt',
    category: 'Bottoms',
    description: 'Flowing pleated midi skirt with an elasticated waist. Moves beautifully with every step. Ideal for the office or a garden party.',
    price: 55.99,
    colours: ['Sage', 'Blush', 'Black', 'Ivory', 'Terracotta'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['work', 'casual', 'party', 'wedding-guest'],
    stock: 52,
    gradient: 'from-green-100 via-emerald-50 to-teal-100',
    isNew: false, isSale: false,
    tags: ['pleated', 'midi', 'skirt', 'flowy'],
    rating: 4.7, reviewCount: 134,
    images: ['https://images.unsplash.com/photo-1577900232427-18219b9166a0?auto=format&fit=crop&w=600&q=80'],
    sizingChart: sc(['XS','S','M','L','XL'], 80),
  },
  {
    name: 'High-Waist Tailored Trousers',
    slug: 'high-waist-tailored-trousers',
    category: 'Bottoms',
    description: 'Sharp high-waist tailored trousers with a straight leg and pressed crease. A boardroom-ready essential that commands attention.',
    price: 89.99,
    colours: ['Black', 'Camel', 'Charcoal', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['work', 'formal', 'meeting'],
    stock: 40,
    gradient: 'from-gray-200 via-slate-100 to-gray-300',
    isNew: true, isSale: false,
    tags: ['tailored', 'trousers', 'work', 'formal'],
    rating: 4.5, reviewCount: 97,
    images: ['https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=80'],
    sizingChart: sc(['XS','S','M','L','XL'], 102),
  },

  // ─── OUTERWEAR ───────────────────────────────────────────────────────────────
  {
    name: '3-in-1 Snowboard Jacket',
    slug: '3-in-1-snowboard-jacket',
    category: 'Outerwear',
    description: 'Detachable design for maximum versatility. Adjustable hood, multiple pockets, and a removable fleece liner for warmth in any season.',
    price: 56.99,
    colours: ['Black', 'Navy', 'Grey'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    occasion: ['outdoor', 'winter', 'ski'],
    stock: 34,
    gradient: 'from-slate-300 via-gray-200 to-slate-400',
    isNew: false, isSale: false,
    tags: ['jacket', 'winter', 'outdoor', 'versatile'],
    rating: 4.2, reviewCount: 78,
    images: [f('51Y5NI-I5jL._AC_UX679_t.png')],
    sizingChart: sc(['XS','S','M','L','XL','XXL'], 76),
  },
  {
    name: 'Faux Leather Biker Jacket',
    slug: 'faux-leather-biker-jacket',
    category: 'Outerwear',
    description: 'Removable hooded faux leather moto biker jacket with polyurethane shell. Edgy, lightweight, and endlessly stylish for any casual outing.',
    price: 29.95,
    colours: ['Black', 'Brown', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['casual', 'night-out', 'everyday'],
    stock: 48,
    gradient: 'from-stone-800 via-stone-600 to-stone-900',
    isNew: false, isSale: true,
    salePrice: 22.99,
    tags: ['leather', 'biker', 'jacket', 'edgy'],
    rating: 3.9, reviewCount: 115,
    images: [f('81XH0e8fefL._AC_UY879_t.png')],
    sizingChart: sc(['XS','S','M','L','XL'], 58),
  },
  {
    name: 'Striped Windbreaker Raincoat',
    slug: 'striped-windbreaker-raincoat',
    category: 'Outerwear',
    description: 'Lightweight women\'s raincoat with an adjustable drawstring waist, lined hood, and striped detailing. Packable and perfect for travel.',
    price: 39.99,
    colours: ['Navy Stripe', 'Black Stripe', 'Pink Stripe'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    occasion: ['outdoor', 'travel', 'casual', 'rainy-day'],
    stock: 27,
    gradient: 'from-indigo-100 via-blue-50 to-indigo-200',
    isNew: true, isSale: false,
    tags: ['raincoat', 'windbreaker', 'travel', 'lightweight'],
    rating: 4.1, reviewCount: 63,
    images: [f('71HblAHs5xL._AC_UY879_-2t.png')],
    sizingChart: sc(['XS','S','M','L','XL'], 82),
  },

  // ─── ACCESSORIES — bags ───────────────────────────────────────────────────────
  {
    name: 'Blue Structured Handbag',
    slug: 'blue-structured-handbag',
    category: 'Accessories',
    description: 'A structured blue handbag with polished hardware and a spacious interior. Elevates any outfit from casual to chic.',
    price: 49.99,
    colours: ['Blue', 'Navy'],
    sizes: ['One Size'],
    occasion: ['everyday', 'work', 'casual'],
    stock: 76,
    gradient: 'from-blue-200 via-sky-100 to-blue-300',
    isNew: false, isSale: false,
    tags: ['handbag', 'structured', 'everyday', 'blue'],
    rating: 2.9, reviewCount: 34,
    images: [d("womens-bags/blue-women's-handbag")],
  },
  {
    name: 'Heshe Leather Shoulder Bag',
    slug: 'heshe-leather-shoulder-bag',
    category: 'Accessories',
    description: 'Premium full-grain leather shoulder bag with a timeless silhouette. Rich detailing and durable construction make this a lifelong investment piece.',
    price: 129.99,
    colours: ['Tan', 'Black', 'Burgundy'],
    sizes: ['One Size'],
    occasion: ['work', 'casual', 'everyday'],
    stock: 99,
    gradient: 'from-amber-100 via-stone-50 to-amber-200',
    isNew: true, isSale: false,
    tags: ['leather', 'shoulder-bag', 'premium', 'classic'],
    rating: 4.9, reviewCount: 201,
    images: [d("womens-bags/heshe-women's-leather-bag")],
  },
  {
    name: 'Prada Chain Shoulder Bag',
    slug: 'prada-chain-shoulder-bag',
    category: 'Accessories',
    description: 'Iconic chain-strap shoulder bag in supple Italian leather. A luxury statement piece that defines understated elegance.',
    price: 599.99,
    colours: ['Black', 'Nude', 'White'],
    sizes: ['One Size'],
    occasion: ['formal', 'evening', 'gala'],
    stock: 75,
    gradient: 'from-neutral-200 via-stone-100 to-neutral-300',
    isNew: false, isSale: false,
    tags: ['luxury', 'chain-bag', 'designer', 'evening'],
    rating: 2.7, reviewCount: 18,
    images: [d('womens-bags/prada-women-bag')],
  },
  {
    name: 'Faux Leather Backpack',
    slug: 'faux-leather-backpack',
    category: 'Accessories',
    description: 'White faux leather backpack with a modern minimalist design. Fits a laptop and daily essentials — from campus to commute.',
    price: 39.99,
    colours: ['White', 'Black', 'Blush'],
    sizes: ['One Size'],
    occasion: ['casual', 'everyday', 'travel'],
    stock: 39,
    gradient: 'from-gray-50 via-white to-gray-100',
    isNew: false, isSale: true,
    salePrice: 29.99,
    tags: ['backpack', 'faux-leather', 'casual', 'everyday'],
    rating: 3.4, reviewCount: 55,
    images: [d('womens-bags/white-faux-leather-backpack')],
  },
  {
    name: 'Classic Black Handbag',
    slug: 'classic-black-handbag',
    category: 'Accessories',
    description: 'A wardrobe-essential black handbag with clean lines and a top-handle design. Goes with everything from workwear to weekend looks.',
    price: 59.99,
    colours: ['Black'],
    sizes: ['One Size'],
    occasion: ['work', 'casual', 'formal', 'everyday'],
    stock: 11,
    gradient: 'from-gray-900 via-gray-800 to-gray-900',
    isNew: false, isSale: false,
    tags: ['handbag', 'black', 'classic', 'essential'],
    rating: 2.9, reviewCount: 29,
    images: [d('womens-bags/women-handbag-black')],
  },
  {
    name: 'Woven Straw Tote',
    slug: 'woven-straw-tote',
    category: 'Accessories',
    description: 'A chic handwoven straw tote with leather handles and a cotton lining. The ultimate summer beach bag that doubles as a market tote.',
    price: 34.99,
    colours: ['Natural', 'Black Trim'],
    sizes: ['One Size'],
    occasion: ['beach', 'casual', 'summer', 'holiday'],
    stock: 56,
    gradient: 'from-amber-100 via-yellow-50 to-amber-200',
    isNew: true, isSale: false,
    tags: ['straw', 'tote', 'beach', 'summer'],
    rating: 4.6, reviewCount: 88,
    images: [d("womens-bags/blue-women's-handbag", 2)],
  },
  {
    name: 'Mini Quilted Crossbody Bag',
    slug: 'mini-quilted-crossbody-bag',
    category: 'Accessories',
    description: 'A compact quilted crossbody bag with a gold chain strap and a magnetic closure. Holds your essentials with effortless style.',
    price: 89.99,
    colours: ['Black', 'Blush', 'Ivory', 'Navy'],
    sizes: ['One Size'],
    occasion: ['casual', 'evening', 'party', 'everyday'],
    stock: 42,
    gradient: 'from-neutral-200 via-stone-100 to-neutral-300',
    isNew: false, isSale: false,
    tags: ['quilted', 'crossbody', 'mini', 'chain-strap'],
    rating: 4.7, reviewCount: 134,
    images: [d("womens-bags/heshe-women's-leather-bag", 2)],
  },
  {
    name: 'Velvet Evening Clutch',
    slug: 'velvet-evening-clutch',
    category: 'Accessories',
    description: 'An elegant velvet clutch bag with a gold-tone frame closure and a detachable chain strap. The perfect finishing touch for formal events and weddings.',
    price: 54.99,
    colours: ['Emerald', 'Burgundy', 'Midnight Blue', 'Black'],
    sizes: ['One Size'],
    occasion: ['formal', 'evening', 'gala', 'wedding'],
    stock: 33,
    gradient: 'from-emerald-200 via-teal-100 to-emerald-300',
    isNew: true, isSale: false,
    tags: ['velvet', 'clutch', 'evening', 'formal'],
    rating: 4.8, reviewCount: 57,
    images: [d('womens-bags/prada-women-bag', 2)],
  },
  {
    name: 'Canvas Weekend Tote',
    slug: 'canvas-weekend-tote',
    category: 'Accessories',
    description: 'A roomy canvas tote with reinforced leather handles and an interior zip pocket. Practical, durable, and stylish for work, gym, or weekend trips.',
    price: 44.99,
    colours: ['Natural', 'Black', 'Navy', 'Olive'],
    sizes: ['One Size'],
    occasion: ['casual', 'everyday', 'travel', 'work'],
    stock: 88,
    gradient: 'from-stone-100 via-amber-50 to-stone-200',
    isNew: false, isSale: true,
    salePrice: 32.99,
    tags: ['canvas', 'tote', 'everyday', 'practical'],
    rating: 4.5, reviewCount: 176,
    images: [d('womens-bags/white-faux-leather-backpack', 2)],
  },
  {
    name: 'Croc-Effect Mini Bag',
    slug: 'croc-effect-mini-bag',
    category: 'Accessories',
    description: 'A statement mini bag in bold croc-embossed faux leather with a top handle and removable strap. Small but mighty.',
    price: 69.99,
    colours: ['Black', 'Cognac', 'White', 'Sage'],
    sizes: ['One Size'],
    occasion: ['casual', 'party', 'evening', 'date'],
    stock: 37,
    gradient: 'from-stone-300 via-stone-200 to-stone-400',
    isNew: true, isSale: false,
    tags: ['croc', 'mini-bag', 'statement', 'top-handle'],
    rating: 4.6, reviewCount: 72,
    images: [d('womens-bags/women-handbag-black', 2)],
  },

  // ─── ACCESSORIES — shoes ──────────────────────────────────────────────────────
  {
    name: 'Dual-Tone Comfort Slippers',
    slug: 'dual-tone-comfort-slippers',
    category: 'Accessories',
    description: 'Black and brown slip-on slippers with a cushioned footbed. Effortless comfort for at-home relaxation or casual outdoor errands.',
    price: 19.99,
    colours: ['Black', 'Brown'],
    sizes: ['36', '37', '38', '39', '40', '41'],
    occasion: ['casual', 'everyday', 'loungewear'],
    stock: 3,
    gradient: 'from-stone-200 via-stone-100 to-stone-300',
    isNew: false, isSale: false,
    tags: ['slippers', 'comfort', 'casual', 'flat'],
    rating: 2.5, reviewCount: 22,
    images: [d('womens-shoes/black-&-brown-slipper')],
  },
  {
    name: 'Calvin Klein Block Heel',
    slug: 'calvin-klein-block-heel',
    category: 'Accessories',
    description: 'Sleek Calvin Klein block-heel shoes with a pointed toe and clean leather finish. Elevated yet comfortable — from boardroom to dinner.',
    price: 79.99,
    colours: ['Black', 'Nude', 'White'],
    sizes: ['36', '37', '38', '39', '40'],
    occasion: ['work', 'formal', 'dinner', 'evening'],
    stock: 93,
    gradient: 'from-neutral-100 via-stone-50 to-neutral-200',
    isNew: true, isSale: false,
    tags: ['heels', 'block-heel', 'formal', 'designer'],
    rating: 4.9, reviewCount: 187,
    images: [d('womens-shoes/calvin-klein-heel-shoes')],
  },
  {
    name: 'Gold Strappy Sandals',
    slug: 'gold-strappy-sandals',
    category: 'Accessories',
    description: 'Glittering gold strappy sandals with a slender heel. The go-to shoe for weddings, parties, and any occasion that calls for a touch of sparkle.',
    price: 49.99,
    colours: ['Gold', 'Silver'],
    sizes: ['36', '37', '38', '39', '40'],
    occasion: ['wedding', 'party', 'formal', 'evening'],
    stock: 88,
    gradient: 'from-yellow-100 via-amber-50 to-yellow-200',
    isNew: true, isSale: false,
    tags: ['sandals', 'gold', 'strappy', 'party'],
    rating: 3.3, reviewCount: 54,
    images: [d('womens-shoes/golden-shoes-woman')],
  },
  {
    name: 'Pampi Casual Flats',
    slug: 'pampi-casual-flats',
    category: 'Accessories',
    description: 'Lightweight and flexible casual flat shoes with a cushioned sole. All-day comfort for errands, travel, and everyday life.',
    price: 29.99,
    colours: ['Beige', 'Black', 'White'],
    sizes: ['36', '37', '38', '39', '40', '41'],
    occasion: ['casual', 'everyday', 'travel'],
    stock: 49,
    gradient: 'from-stone-100 via-amber-50 to-stone-200',
    isNew: false, isSale: true,
    salePrice: 21.99,
    tags: ['flats', 'casual', 'comfortable', 'everyday'],
    rating: 3.1, reviewCount: 39,
    images: [d('womens-shoes/pampi-shoes')],
  },
  {
    name: 'Red Patent Heels',
    slug: 'red-patent-heels',
    category: 'Accessories',
    description: 'Bold red patent-leather heels with a classic stiletto silhouette. A head-turning statement piece for evenings and special occasions.',
    price: 89.99,
    colours: ['Red', 'Black'],
    sizes: ['36', '37', '38', '39', '40'],
    occasion: ['evening', 'party', 'formal'],
    stock: 35,
    gradient: 'from-red-200 via-rose-100 to-red-300',
    isNew: false, isSale: false,
    tags: ['heels', 'red', 'patent', 'bold'],
    rating: 4.6, reviewCount: 88,
    images: [d('womens-shoes/red-heels')],
  },
  {
    name: 'Pointed Toe Mules',
    slug: 'pointed-toe-mules',
    category: 'Accessories',
    description: 'Sleek slip-on mules with a pointed toe and a mid block heel. Versatile and polished — dresses up jeans and elevates any daytime outfit.',
    price: 74.99,
    colours: ['Black', 'Nude', 'White', 'Tan'],
    sizes: ['36', '37', '38', '39', '40'],
    occasion: ['work', 'casual', 'smart-casual'],
    stock: 61,
    gradient: 'from-stone-100 via-neutral-50 to-stone-200',
    isNew: true, isSale: false,
    tags: ['mules', 'pointed', 'block-heel', 'versatile'],
    rating: 4.5, reviewCount: 118,
    images: [d('womens-shoes/black-&-brown-slipper', 2)],
  },
  {
    name: 'Block Heel Ankle Boots',
    slug: 'block-heel-ankle-boots',
    category: 'Accessories',
    description: 'Suede ankle boots with a sturdy block heel and a side zip. Walk confidently all day — these boots are as comfortable as they are stylish.',
    price: 129.99,
    colours: ['Black', 'Tan', 'Burgundy', 'Grey'],
    sizes: ['36', '37', '38', '39', '40', '41'],
    occasion: ['casual', 'work', 'everyday', 'autumn'],
    stock: 49,
    gradient: 'from-stone-300 via-stone-200 to-stone-400',
    isNew: false, isSale: false,
    tags: ['ankle-boots', 'block-heel', 'suede', 'autumn'],
    rating: 4.7, reviewCount: 164,
    images: [d('womens-shoes/calvin-klein-heel-shoes', 2)],
  },
  {
    name: 'White Platform Trainers',
    slug: 'white-platform-trainers',
    category: 'Accessories',
    description: 'Clean white platform trainers with a chunky rubber sole and a lace-up front. Adds height and edge to any casual outfit.',
    price: 85.99,
    colours: ['White', 'White/Black', 'White/Pink'],
    sizes: ['36', '37', '38', '39', '40', '41'],
    occasion: ['casual', 'everyday', 'weekend'],
    stock: 72,
    gradient: 'from-gray-50 via-white to-gray-100',
    isNew: true, isSale: false,
    tags: ['trainers', 'platform', 'white', 'casual'],
    rating: 4.4, reviewCount: 203,
    images: [d('womens-shoes/golden-shoes-woman', 2)],
  },
  {
    name: 'Kitten Heel Slingbacks',
    slug: 'kitten-heel-slingbacks',
    category: 'Accessories',
    description: 'Classic kitten-heel slingbacks with a pointed toe and an adjustable ankle strap. Chic, comfortable, and endlessly elegant.',
    price: 95.99,
    colours: ['Black', 'Nude', 'White', 'Blush'],
    sizes: ['36', '37', '38', '39', '40'],
    occasion: ['work', 'formal', 'casual', 'wedding'],
    stock: 54,
    gradient: 'from-neutral-100 via-stone-50 to-neutral-200',
    isNew: false, isSale: false,
    tags: ['kitten-heel', 'slingback', 'classic', 'elegant'],
    rating: 4.6, reviewCount: 97,
    images: [d('womens-shoes/pampi-shoes', 2)],
  },
  {
    name: 'Espadrille Wedge Sandals',
    slug: 'espadrille-wedge-sandals',
    category: 'Accessories',
    description: 'Rope-wrapped espadrille wedge sandals with a crossed ankle strap. A summer essential that adds height without sacrificing comfort.',
    price: 64.99,
    colours: ['Natural', 'Black', 'Tan', 'White'],
    sizes: ['36', '37', '38', '39', '40'],
    occasion: ['casual', 'beach', 'summer', 'holiday'],
    stock: 68,
    gradient: 'from-amber-100 via-yellow-50 to-amber-200',
    isNew: false, isSale: true,
    salePrice: 48.99,
    tags: ['espadrille', 'wedge', 'sandals', 'summer'],
    rating: 4.5, reviewCount: 141,
    images: [d('womens-shoes/red-heels', 2)],
  },

  // ─── ACCESSORIES — jewellery ──────────────────────────────────────────────────
  {
    name: 'Green Crystal Drop Earrings',
    slug: 'green-crystal-drop-earrings',
    category: 'Accessories',
    description: 'Sparkling green crystal drop earrings set in polished silver. Adds instant glamour to an evening look or dresses up a daytime outfit.',
    price: 29.99,
    colours: ['Green', 'Silver'],
    sizes: ['One Size'],
    occasion: ['evening', 'formal', 'party', 'wedding'],
    stock: 54,
    gradient: 'from-emerald-100 via-green-50 to-emerald-200',
    isNew: true, isSale: false,
    tags: ['earrings', 'crystal', 'green', 'glamour'],
    rating: 4, reviewCount: 62,
    images: [d('womens-jewellery/green-crystal-earring')],
  },
  {
    name: 'Green Oval Statement Earrings',
    slug: 'green-oval-statement-earrings',
    category: 'Accessories',
    description: 'Oversized oval earrings in a vibrant green finish. Bold, architectural jewellery that makes a statement without saying a word.',
    price: 24.99,
    colours: ['Green', 'Gold'],
    sizes: ['One Size'],
    occasion: ['casual', 'party', 'work'],
    stock: 73,
    gradient: 'from-teal-100 via-green-50 to-teal-200',
    isNew: false, isSale: true,
    salePrice: 18.99,
    tags: ['earrings', 'statement', 'oval', 'bold'],
    rating: 3.6, reviewCount: 41,
    images: [d('womens-jewellery/green-oval-earring')],
  },
  {
    name: 'Tropical Floral Earrings',
    slug: 'tropical-floral-earrings',
    category: 'Accessories',
    description: 'Fun and vibrant tropical-themed earrings with hand-painted floral details. The perfect finishing touch for summer looks and holidays.',
    price: 19.99,
    colours: ['Multi', 'Gold'],
    sizes: ['One Size'],
    occasion: ['casual', 'beach', 'holiday', 'summer'],
    stock: 1,
    gradient: 'from-orange-100 via-yellow-50 to-orange-200',
    isNew: false, isSale: false,
    tags: ['earrings', 'tropical', 'summer', 'fun'],
    rating: 4.4, reviewCount: 77,
    images: [d('womens-jewellery/tropical-earring')],
  },
  {
    name: 'Pearl Pendant Necklace',
    slug: 'pearl-pendant-necklace',
    category: 'Accessories',
    description: 'A classic freshwater pearl pendant on a fine gold-plated chain. Timeless and elegant — worn alone or layered for a modern touch.',
    price: 44.99,
    colours: ['Gold', 'Silver'],
    sizes: ['One Size'],
    occasion: ['formal', 'work', 'casual', 'wedding'],
    stock: 78,
    gradient: 'from-neutral-100 via-stone-50 to-neutral-200',
    isNew: false, isSale: false,
    tags: ['pearl', 'necklace', 'classic', 'elegant'],
    rating: 4.7, reviewCount: 143,
    images: [d('womens-jewellery/green-crystal-earring', 2)],
  },
  {
    name: 'Gold Layered Chain Necklace',
    slug: 'gold-layered-chain-necklace',
    category: 'Accessories',
    description: 'A set of three delicate gold-tone chains in varying lengths designed to be worn together. Effortlessly adds texture and dimension to any neckline.',
    price: 34.99,
    colours: ['Gold', 'Rose Gold', 'Silver'],
    sizes: ['One Size'],
    occasion: ['casual', 'party', 'everyday', 'date'],
    stock: 93,
    gradient: 'from-yellow-100 via-amber-50 to-yellow-200',
    isNew: true, isSale: false,
    tags: ['necklace', 'layered', 'gold', 'chain'],
    rating: 4.5, reviewCount: 218,
    images: [d('womens-jewellery/green-oval-earring', 2)],
  },
  {
    name: 'Silver Hoop Earrings',
    slug: 'silver-hoop-earrings',
    category: 'Accessories',
    description: 'Polished sterling-silver hoop earrings in a medium size. A wardrobe essential that goes from day to night without missing a beat.',
    price: 24.99,
    colours: ['Silver', 'Gold'],
    sizes: ['One Size'],
    occasion: ['casual', 'everyday', 'work', 'party'],
    stock: 120,
    gradient: 'from-gray-100 via-slate-50 to-gray-200',
    isNew: false, isSale: false,
    tags: ['earrings', 'hoops', 'silver', 'classic'],
    rating: 4.8, reviewCount: 376,
    images: [d('womens-jewellery/tropical-earring', 2)],
  },
  {
    name: 'Crystal Stud Earrings',
    slug: 'crystal-stud-earrings',
    category: 'Accessories',
    description: 'Sparkling round crystal stud earrings set in gold-plated sterling silver. Understated glamour that complements every look.',
    price: 28.99,
    colours: ['Clear/Gold', 'Clear/Silver', 'Pink/Rose Gold'],
    sizes: ['One Size'],
    occasion: ['formal', 'everyday', 'wedding', 'work'],
    stock: 87,
    gradient: 'from-sky-100 via-blue-50 to-sky-200',
    isNew: false, isSale: true,
    salePrice: 20.99,
    tags: ['earrings', 'crystal', 'studs', 'subtle'],
    rating: 4.6, reviewCount: 205,
    images: [d('womens-jewellery/green-crystal-earring', 3)],
  },
  {
    name: 'Gold Charm Bracelet',
    slug: 'gold-charm-bracelet',
    category: 'Accessories',
    description: 'A delicate gold-tone chain bracelet with a set of miniature charms — heart, star, and crescent moon. A personal and sentimental everyday accessory.',
    price: 38.99,
    colours: ['Gold', 'Rose Gold', 'Silver'],
    sizes: ['One Size'],
    occasion: ['casual', 'everyday', 'gift'],
    stock: 64,
    gradient: 'from-yellow-100 via-amber-50 to-yellow-200',
    isNew: true, isSale: false,
    tags: ['bracelet', 'charm', 'gold', 'delicate'],
    rating: 4.4, reviewCount: 131,
    images: [d('womens-jewellery/green-oval-earring', 3)],
  },
  {
    name: 'Tortoiseshell Cuff Bracelet',
    slug: 'tortoiseshell-cuff-bracelet',
    category: 'Accessories',
    description: 'A bold tortoiseshell-print resin cuff bracelet with an open back for an adjustable fit. Makes a statement whether worn alone or stacked.',
    price: 48.99,
    colours: ['Tortoiseshell', 'Black', 'Cream'],
    sizes: ['One Size'],
    occasion: ['casual', 'party', 'work'],
    stock: 44,
    gradient: 'from-amber-200 via-stone-200 to-amber-300',
    isNew: false, isSale: false,
    tags: ['bracelet', 'cuff', 'statement', 'resin'],
    rating: 4.3, reviewCount: 66,
    images: [d('womens-jewellery/tropical-earring', 3)],
  },

  // ─── ACCESSORIES — watches ────────────────────────────────────────────────────
  {
    name: 'IWC Ingenieur Automatic Watch',
    slug: 'iwc-ingenieur-automatic-watch',
    category: 'Accessories',
    description: 'A prestigious automatic steel watch with an elegant dial and Swiss movement. Technical precision meets timeless design in this collector\'s piece.',
    price: 4999.99,
    colours: ['Silver/White', 'Silver/Black'],
    sizes: ['One Size'],
    occasion: ['formal', 'work', 'everyday'],
    stock: 5,
    gradient: 'from-gray-200 via-slate-100 to-gray-300',
    isNew: false, isSale: false,
    tags: ['watch', 'luxury', 'automatic', 'swiss'],
    rating: 4.9, reviewCount: 12,
    images: [d('womens-watches/iwc-ingenieur-automatic-steel')],
  },
  {
    name: 'Rolex Cellini Moonphase Watch',
    slug: 'rolex-cellini-moonphase-watch',
    category: 'Accessories',
    description: 'An iconic Rolex Cellini with a stunning moonphase complication and a classic Oyster case. The pinnacle of horological craftsmanship.',
    price: 15999.99,
    colours: ['Gold', 'Rose Gold'],
    sizes: ['One Size'],
    occasion: ['formal', 'gala', 'special-occasion'],
    stock: 3,
    gradient: 'from-yellow-200 via-amber-100 to-yellow-300',
    isNew: false, isSale: false,
    tags: ['watch', 'rolex', 'luxury', 'moonphase'],
    rating: 5, reviewCount: 8,
    images: [d('womens-watches/rolex-cellini-moonphase')],
  },
  {
    name: 'Rolex Datejust Women\'s Watch',
    slug: 'rolex-datejust-womens-watch',
    category: 'Accessories',
    description: 'The legendary Rolex Datejust in a women\'s size with a date display and an Oyster bracelet. An enduring icon of style and precision.',
    price: 10999.99,
    colours: ['Steel', 'Two-Tone', 'Rose Gold'],
    sizes: ['One Size'],
    occasion: ['formal', 'work', 'everyday', 'special-occasion'],
    stock: 4,
    gradient: 'from-gray-100 via-slate-50 to-gray-200',
    isNew: false, isSale: false,
    tags: ['watch', 'rolex', 'datejust', 'luxury'],
    rating: 4.9, reviewCount: 15,
    images: [d('womens-watches/rolex-datejust-women')],
  },
  {
    name: 'Gold Tone Dress Watch',
    slug: 'gold-tone-dress-watch',
    category: 'Accessories',
    description: 'A refined gold-tone dress watch with a slim case and a minimalist dial. Understated luxury for the woman who appreciates quiet elegance.',
    price: 799.99,
    colours: ['Gold', 'Rose Gold'],
    sizes: ['One Size'],
    occasion: ['formal', 'work', 'everyday'],
    stock: 18,
    gradient: 'from-yellow-100 via-amber-50 to-yellow-200',
    isNew: true, isSale: false,
    tags: ['watch', 'gold', 'dress-watch', 'elegant'],
    rating: 4.6, reviewCount: 29,
    images: [d('womens-watches/watch-gold-for-women')],
  },
  {
    name: 'Classic Silver Watch',
    slug: 'classic-silver-watch',
    category: 'Accessories',
    description: 'A beautifully crafted silver-tone ladies\' watch with a clean dial and a comfortable mesh bracelet. Versatile and timeless for everyday wear.',
    price: 129.99,
    colours: ['Silver', 'Silver/White'],
    sizes: ['One Size'],
    occasion: ['casual', 'work', 'everyday'],
    stock: 45,
    gradient: 'from-gray-100 via-slate-50 to-gray-200',
    isNew: false, isSale: true,
    salePrice: 99.99,
    tags: ['watch', 'silver', 'mesh-bracelet', 'classic'],
    rating: 4.4, reviewCount: 67,
    images: [d("womens-watches/women's-wrist-watch")],
  },

  // ─── ACCESSORIES — sunglasses ─────────────────────────────────────────────────
  {
    name: 'Oversized Black Sunglasses',
    slug: 'oversized-black-sunglasses',
    category: 'Accessories',
    description: 'Bold oversized sunglasses with UV400 lenses and a lightweight acetate frame. Classic glamour with serious sun protection.',
    price: 29.99,
    colours: ['Black'],
    sizes: ['One Size'],
    occasion: ['casual', 'beach', 'everyday', 'summer'],
    stock: 95,
    gradient: 'from-gray-800 via-gray-700 to-gray-900',
    isNew: false, isSale: false,
    tags: ['sunglasses', 'oversized', 'black', 'uv-protection'],
    rating: 4.3, reviewCount: 88,
    images: [d('sunglasses/black-sun-glasses')],
  },
  {
    name: 'Classic Tortoiseshell Sunglasses',
    slug: 'classic-tortoiseshell-sunglasses',
    category: 'Accessories',
    description: 'Timeless tortoiseshell-frame sunglasses in a flattering cat-eye shape with polarised lenses. A wardrobe classic that never goes out of style.',
    price: 24.99,
    colours: ['Tortoiseshell', 'Black'],
    sizes: ['One Size'],
    occasion: ['casual', 'everyday', 'beach', 'summer'],
    stock: 83,
    gradient: 'from-amber-200 via-stone-200 to-amber-300',
    isNew: false, isSale: true,
    salePrice: 17.99,
    tags: ['sunglasses', 'tortoiseshell', 'classic', 'cat-eye'],
    rating: 4.5, reviewCount: 124,
    images: [d('sunglasses/classic-sun-glasses')],
  },
  {
    name: 'Retro Green Tinted Sunglasses',
    slug: 'retro-green-tinted-sunglasses',
    category: 'Accessories',
    description: 'Retro-inspired sunglasses with green-tinted lenses and a two-tone frame. A playful and fashion-forward choice for summer styling.',
    price: 34.99,
    colours: ['Green/Black', 'Green/Clear'],
    sizes: ['One Size'],
    occasion: ['casual', 'summer', 'beach', 'festival'],
    stock: 61,
    gradient: 'from-green-100 via-emerald-50 to-green-200',
    isNew: true, isSale: false,
    tags: ['sunglasses', 'tinted', 'retro', 'festival'],
    rating: 4.4, reviewCount: 63,
    images: [d('sunglasses/green-and-black-glasses')],
  },
  {
    name: 'Fun Party Glasses',
    slug: 'fun-party-glasses',
    category: 'Accessories',
    description: 'Eye-catching novelty party glasses in a bold geometric shape. Add a burst of personality to festival outfits or any occasion that calls for fun.',
    price: 19.99,
    colours: ['Multi', 'Pink', 'Yellow'],
    sizes: ['One Size'],
    occasion: ['party', 'festival', 'casual'],
    stock: 120,
    gradient: 'from-pink-100 via-fuchsia-50 to-pink-200',
    isNew: false, isSale: false,
    tags: ['sunglasses', 'party', 'novelty', 'fun'],
    rating: 4.1, reviewCount: 44,
    images: [d('sunglasses/party-glasses')],
  },
  {
    name: 'Round Retro Sunglasses',
    slug: 'round-retro-sunglasses',
    category: 'Accessories',
    description: 'Perfectly round retro-style sunglasses with flat lenses and a thin metal frame. A minimalist festival staple inspired by the 1960s.',
    price: 22.99,
    colours: ['Gold/Brown', 'Silver/Grey', 'Black'],
    sizes: ['One Size'],
    occasion: ['casual', 'festival', 'everyday'],
    stock: 77,
    gradient: 'from-amber-100 via-yellow-50 to-amber-200',
    isNew: false, isSale: false,
    tags: ['sunglasses', 'round', 'retro', 'metal-frame'],
    rating: 4.3, reviewCount: 79,
    images: [d('sunglasses/sunglasses')],
  },
]
